internal/compiler/wasm: commit generated wasm
I've noticed that since the CI build running on macos-latest doesn't
have docker installed, it cannot update these files itself at build
time. We thus end up with macos binaries that have the wasm binary
data from the main branch, not the PR.

This can be observed from the test failure:

    Run make ci-binary-smoke-test-wasm BINARY=opa_darwin_amd64
    chmod +x "_release/0.31.0-dev/opa_darwin_amd64"
    "_release/0.31.0-dev/opa_darwin_amd64" eval -t "wasm" 'time.now_ns()'
    make: *** [ci-binary-smoke-test-wasm] Error 2
    {
      "errors": [
        {
          "message": "caller not found: opa_eval (opa_eval)"
        }
      ]
    }
    Error: Process completed with exit code 2.

Since I had previously commit the CSV data that drives the dead
code elimination process, that optimization had failed to find a
function it expected to have.

Signed-off-by: Stephan Renatus <stephan.renatus@gmail.com>